all: lab01.ipynb lab02.ipynb lab03.ipynb

lab01.ipynb: labs/lab01.md
	notedown labs/lab01.md > lab01.ipynb

lab02.ipynb: labs/lab02.md
	notedown labs/lab02.md > lab02.ipynb

lab03.ipynb: labs/lab03.md
	notedown labs/lab03.md > lab03.ipynb

